---
# Site settings
title: Paulo Fidalgo
description: Paulo Fidalgo is an accomplished software engineering leader passionate about creating customer-centric products through expertise in backend software and distributed systems. With almost a decade of experience working remotely, he brings business and product-oriented insights to every project he undertakes.
baseurl: "" #the subpath of your site, e.g. /blog/
url: "http://www.fidalgo.pt" # the base hostname & protocol for your site
date_format: "%B %-d, %Y"
twitter: "https://twitter.com/kanniball"
github: "https://github.com/fidalgo"
stackoverflow: "https://stackoverflow.com/u/1006863"
linkedin: "https://www.linkedin.com/in/fidalgo"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: :compressed

paginate: 10

collections:
  - positions

plugins:
  - jekyll-paginate
  - jekyll-sitemap
