---
# Site settings
title: Paulo Fidalgo
email: paulo.fidalgo.pt@gmail.com
description: Paulo Fidalgo is a Ruby passionate, entrepreneur and a backend software engineer that loves to work remotely.
baseurl: "" #the subpath of your site, e.g. /blog/
url: "https://www.fidalgo.pt" # the base hostname & protocol for your site
date_format: "%B %-d, %Y"
twitter: "https://twitter.com/kanniball"
github: "https://github.com/fidalgo"
stackoverflow: "https://stackoverflow.com/u/1006863"
linkedin: "https://www.linkedin.com/in/fidalgo"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: :compressed

paginate: 10

collections:
  - positions

plugins:
  - jekyll-paginate
  - jekyll-sitemap
