# Site settings
title: Paulo Fidalgo
email: paulo.fidalgo.pt@gmail.com
description: Resume of Paulo Fidalgo a software engineer with Ruby on Rails and Hadoop skills.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fidalgo.github.io" # the base hostname & protocol for your site
twitter_username: kanniball
github_username:  fidalgo
stackoverflow_profile_url: 'http://stackoverflow.com/users/1006863/paulo-fidalgo?tab=profile'

# Build settings
markdown: kramdown
