# Site settings
title: Paulo Fidalgo
email: paulo.fidalgo.pt@gmail.com
description: Paulo Fidalgo is a Ruby passionate, entrepreneur and a remote backend software engineer at Talkdesk.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fidalgo.github.io" # the base hostname & protocol for your site
date_format: "%B %-d, %Y"
twitter_username: kanniball
github_username:  fidalgo
stackoverflow_profile_url: 'http://stackoverflow.com/users/1006863/paulo-fidalgo?tab=profile'
linkedin_profile_url: 'https://pt.linkedin.com/in/fidalgo'

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
    style: :compressed

paginate:     4

collections:
- positions

gems:
  - jekyll-paginate
  - jekyll-sitemap
